# Directory: .github/workflows/ci.yml
name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request: {}
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend
        run: |
          cd backend
          docker build -t backend .

      - name: Build frontend
        run: |
          cd frontend
          docker build -t frontend .

      - name: Validate Docker Hub Secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME secret is missing"; exit 1;
          fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN secret is missing"; exit 1;
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run AI test predictor
        run: |
          pip install -r ai/requirements.txt || echo 'requirements.txt not found'
          python ai/log_classifier.py || echo 'log_classifier.py failed'

      - name: Run Slack alert test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Testing Slack alert..."
          python tests/test_slack_alert.py || echo 'Slack alert test failed'
