name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  BACKEND_IMAGE: lehqan/backend
  FRONTEND_IMAGE: lehqan/frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend
        run: |
          cd backend
          docker build -t $BACKEND_IMAGE:latest .
          docker push $BACKEND_IMAGE:latest

      - name: Build frontend
        run: |
          cd frontend
          docker build -t  $FRONTEND_IMAGE:latest .
          docker push  $FRONTEND_IMAGE:latest

      - name: Run AI test predictor
        run: |
          pip install -r ai/requirements.txt || echo 'requirements.txt not found'
          python ai/log_classifier.py || echo 'log_classifier.py failed'

      - name: Run Slack alert test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Testing Slack alert..."
          python tests/test_slack_alert.py || echo 'Slack alert test failed'